name: build-test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  BUILD_TYPE: Release
  QT_QPA_PLATFORM: offscreen
  XDG_RUNTIME_DIR: '/tmp/runtime-runner'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        experimental: [false]

    steps:
      - name: Update deps
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get update
             elif [ "$RUNNER_OS" == "macOS" ]; then
               brew update
             fi
        shell: bash

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}
          variant: sccache

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache
          version: '6.2.*'

      - name: Install BLAST
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get install -y ncbi-blast+
             elif [ "$RUNNER_OS" == "macOS" ]; then
               brew install blast
             fi
        shell: bash

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_C_COMPILER_LAUNCHER=sccache -D CMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j8

      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V

      - name: CLI Tests
        working-directory: ${{github.workspace}}/tests
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               ./bandage_command_line_tests.sh ${{github.workspace}}/build/BandageNG
             elif [ "$RUNNER_OS" == "macOS" ]; then
               brew install imagemagick
               ./bandage_command_line_tests.sh ${{github.workspace}}/build/BandageNG.app/Contents/MacOS/BandageNG
             fi
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: Bandage-${{ runner.os }}
          path: |
             ${{github.workspace}}/build/BandageNG
             ${{github.workspace}}/build/BandageNG.app
             ${{github.workspace}}/build/BandageTests
